
project_id = "bagaaqkmewkuwtudwnqw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:3000/login"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions]
[functions.send-survey-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-test-emails]
verify_jwt = false
