
# Netlify configuration
[build]
  command = "npm run build"
  publish = "dist"
  # Add legacy-peer-deps flag to resolve package conflicts and force a clean build
  environment = { NPM_FLAGS = "--legacy-peer-deps", NETLIFY_EXPERIMENTAL_BUILD_CLEAR_CACHE = "true" }

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add strict cache control headers to prevent browser caching of HTML, JS and CSS
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Add specific cache control for assets that can be cached longer
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Configure functions directory for Supabase functions
[functions]
  directory = "supabase/functions"
